[workspace]
version =  "0.1."
members = ["audido-core", "audido-tui"]
default-members = ["audido-tui"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.100"
tokio = { version = "1.49", features = ["full"] }
log = "0.4.29"
env_logger = "0.11.8"
